-- One row per meaningful user action in the Hub (PDI_100), written fire-and-forget off the request thread by
-- the event-logging-to-db-feature module.
--
-- The column set is the template's 0001-usage-events.xml verbatim, which is itself 1:1 with AI Digital's
-- BigQuery usage_logging_ai_services_table, so a future exporter can ship these rows without remapping them.
-- Its REQUIRED set (event_id, event_timestamp, service, event_type) is the only NOT NULL set here; everything
-- else stays nullable so a partial event still lands rather than being lost to a constraint.
--
-- One departure from the template: event_timestamp is TIMESTAMP(6) WITHOUT TIME ZONE, not TIMESTAMPTZ. This
-- schema is checked at startup (spring.jpa.hibernate.ddl-auto=validate) and UsageEventEntity maps the field as
-- LocalDateTime, which validation reads as TIMESTAMP - a TIMESTAMPTZ column would refuse to boot. The value
-- written is UTC either way, and every other timestamp in this schema is stored the same way.
CREATE TABLE usage_events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- One UUID per event, unique so a retried insert cannot double-count an action.
    event_id        TEXT                           NOT NULL,
    event_timestamp TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    -- Stable lowercase-hyphen service identifier, so rows from several services can share one table.
    service         TEXT                           NOT NULL,
    environment     TEXT,
    -- api_request | auth | error | custom.
    event_type      TEXT                           NOT NULL,
    -- Dotted lowercase action id, e.g. report.create. A stable analytics key: renaming one breaks the
    -- queries a manager has already written against it.
    action          TEXT,
    -- The Clerk user_id claim, never the email address - the email lives in its own column.
    user_id         TEXT,
    user_email      TEXT,
    status          TEXT,
    duration_ms     BIGINT,
    -- Sanitized structured payload: correlation_id, user_name, and per-action keys. Never credentials,
    -- tokens, raw request bodies, or third-party personal data.
    attributes      JSONB,
    error_message   TEXT,
    client_ip       TEXT,
    user_agent      TEXT,
    CONSTRAINT pk_usage_events PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uq_usage_events_event_id ON usage_events (event_id);
-- The two questions a usage query actually asks: what happened for this service lately, and how often was
-- this one action taken lately.
CREATE INDEX idx_usage_events_service_ts ON usage_events (service, event_timestamp DESC);
CREATE INDEX idx_usage_events_action_ts ON usage_events (action, event_timestamp DESC);
